const words = [
  "salmon sushi",
  "ramen",
  "cotton candy",
  "chocolate muffin",
  "doughnut",
  "coconut milk",
  "orange juice",
  "muesli",
  "salami",
  "yogurt",
  "acorn",
  "broccoli ",
  "fish fillet",
  "fried rice ",
  "baguette",
  "bread",
  "sundae",
  "tomyum",
  "longan",
  "gingerbread",
  "margarine",
  "nugget",
  "iceberg lettuce ",
  "pomelo",
  "chives",
  "raspberry jam",
  "carrot cake",
  "beef burrito",
  "apple juice",
  "tomato",
  "whisky",
  "cocoa",
  "pink grapefruit",
  "turbot",
  "panini",
  "artichoke",
  "apple pie",
  "honey",
  "cookie",
  "chicken taco",
  "club sandwich",
  "dim sum ",
  "potato chips",
  "quinoa",
  "bacon",
  "fried bread",
  "teabag",
  "crumpet",
  "marmalade",
  "turkey",
  "salmon",
  "lemon curd",
  "cornflakes",
  "scrambled egg",
  "sesame",
  "mulberry ",
  "apricot jam",
  "brioche",
  "spinach ",
  "waffle",
  "ginger",
  "dumpling",
  "fennel",
  "cupcake",
  "chocolate cake",
  "croissant",
  "buffalo wings",
  "tiramisu ",
  "garden peas",
  "hotdog",
  "aubergine ",
  "pawpaw",
  "mussel",
  "spaghetti ",
  "granola",
  "cheddar cheese",
  "black pudding",
  "bell pepper",
  "mozzarella cheese",
  "raisin",
  "toro sashimi ",
  "boiled egg",
  "conference pear",
  "nougat",
  "carrot",
  "golden syrup",
  "muffin",
  "baked beans",
  "dragon fruit",
  "lasagne",
  "eggs benedict",
  "cherry tomato",
  "butter",
  "almond",
  "cashew",
  "sausages",
  "macaroni ",
  "poached egg",
  "radish",
  "lychee",
  "shrimp",
  "pretzel",
  "celery",
  "shish kebab",
  "goji berry",
  "emmental cheese",
  "garlic",
  "tomato soup",
  "maple syrup",
  "peanut butter",
  "toro nigiri",
  "cabbage ",
  "bagel",
  "porridge",
  "papaya",
  "apple",
  "crayfish",
  "cherry jam",
  "brasil",
  "grapefruit juice",
  "potato",
  "milkshake",
  "curry chicken",
  "strawberry jam",
  "banana",
  "oyster",
  "pudding",
  "kimchi",
  "black pepper",
  "pancake",
  "cheese burger",
  "blackberry jam",
  "walnut",
  "noodle",
  "coffee",
  "red snapper",
  "cereal",
  "fish pie",
  "french fries",
  "cheesecake",
  "apple crumble",
  "dipping sauce",
  "brown sauce",
  "sourdough",
];

const currentWord = () => {
  const startDate = new Date("2023-02-03");
  startDate.setHours(0, 0, 0, 0);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const gameId = Math.floor(
    (today.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)
  );

  const todayWord = words[gameId];
  // const gameDaySession = today.getHours();
  // return gameDaySession < 12 ? wordsAM[gameId] : wordsPM[gameId];
  return {
    today: today,
    gameId: gameId,
    todayWord: todayWord,
  };
};

export { currentWord };
