const words = [
  "orange",
  "mango",
  "pineapple",
  "grape",
  "strawberry",
  "blueberry",
  "watermelon",
  "cherry",
  "peach",
  "plum",
  "kiwi",
  "raspberry",
  "avocado",
  "lemon",
  "lime",
  "grapefruit",
  "pomegranate",
  "blackberry",
  "cranberry",
  "apricot",
  "fig",
  "date",
  "coconut",
  "cantaloupe",
  "honeydew",
  "pear",
  "nectarine",
  "guava",
  "passionfruit",
  "cucumber",
  "broccoli",
  "spinach",
  "lettuce",
  "kale",
  "cabbage",
  "cauliflower",
  "sweet potato",
  "onion",
  "cilantro",
  "basil",
  "mint",
  "thyme",
  "rosemary",
  "sage",
  "oregano",
  "parsley",
  "dill",
  "bay leaf",
  "nutmeg",
  "cinnamon",
  "clove",
  "cardamom",
  "turmeric",
  "coriander",
  "cumin",
  "paprika",
  "chili",
  "salt",
  "sugar",
  "olive oil",
  "canola oil",
  "coconut oil",
  "soy sauce",
  "teriyaki sauce",
  "balsamic vinegar",
  "red wine vinegar",
  "white wine vinegar",
  "mustard",
  "ketchup",
  "mayonnaise",
  "hot sauce",
  "worcestershire sauce",
  "barbecue sauce",
  "salsa",
  "guacamole",
  "hummus",
  "pesto",
  "tzatziki",
  "ranch dressing",
  "caesar dressing",
  "vinaigrette",
  "tomato sauce",
  "alfredo sauce",
  "marinara sauce",
  "cottage cheese",
  "cheddar",
  "mozzarella",
  "parmesan",
  "feta",
  "swiss",
  "gouda",
  "brie",
  "camembert",
  "provolone",
  "ricotta",
  "scrambled eggs",
  "fried egg",
  "chicken",
  "beef",
  "pork",
  "lamb",
  "tuna",
  "crab",
  "lobster",
  "clam",
  "scallop",
  "calamari",
  "octopus",
  "tilapia",
  "cod",
  "haddock",
  "catfish",
  "trout",
  "sole",
  "hamburger",
  "cheeseburger",
  "hot dog",
  "pizza",
  "spaghetti",
  "risotto",
  "sushi",
  "sashimi",
  "falafel",
  "baba ganoush",
  "tabouleh",
  "ratatouille",
  "tempura",
  "pita bread",
  "fajita",
  "quesadilla",
  "enchilada",
  "burrito",
  "taco",
  "nacho",
  "fondue",
  "bruschetta",
  "caprese salad",
  "cobb salad",
  "caesar salad",
  "waldorf salad",
  "nicoise salad",
  "greek salad",
  "coleslaw",
  "potato salad",
  "macaroni salad",
  "pasta salad",
  "chicken salad",
  "tuna salad",
  "egg salad",
  "fruit salad",
  "ambrosia salad",
  "chai tea",
  "green tea",
  "black tea",
  "earl grey",
  "chamomile tea",
  "peppermint tea",
  "limeade",
  "ginger beer",
  "club soda",
  "tonic water",
  "still water",
  "mineral water",
  "cranberry juice",
  "grape juice",
  "pineapple juice",
  "tomato juice",
  "carrot juice",
  "beet juice",
  "champagne",
  "prosecco",
  "red wine",
  "white wine",
  "beer",
  "hard cider",
  "margarita",
  "mojito",
  "martini",
  "cosmopolitan",
  "moscow mule",
  "old fashioned",
  "daiquiri",
  "pina colada",
  "mai tai",
  "sangria",
  "mimosa",
  "bellini",
  "bloody mary",
  "caesar cocktail",
  "manhattan cocktail",
  "negroni",
  "whiskey sour",
  "dark and stormy",
  "mint julep",
  "paloma",
  "tom collins",
  "vesper",
  "sidecar",
  "grits",
  "slaw",
  "toast",
  "jam",
  "jelly",
  "cake",
  "frosting",
  "taffy",
  "dip",
  "guac",
  "wrap",
  "sandwich",
  "sub",
  "salad",
  "fries",
  "onion rings",
  "hash browns",
  "java",
  "brew",
  "hooch",
  "grog",
  "bites",
  "sip",
  "gulp",
  "quaff",
  "swig",
  "chug",
  "slurp",
  "chew",
  "devour",
  "feast",
  "guzzle",
  "banquet",
  "repast",
  "dinner",
  "supper",
  "meal",
  "lunch",
  "brunch",
  "breakfast",
  "treat",
  "delight",
  "yummy",
  "rich",
  "creamy",
  "velvety",
  "smooth",
  "crunchy",
  "crispy",
  "tender",
  "juicy",
  "zesty",
  "sizzling",
  "roasted",
  "grilled",
  "smoked",
  "steamed",
  "boiled",
  "roast",
  "broil",
  "bake",
  "grill",
  "fry",
  "poach",
  "steam",
  "blanch",
  "braise",
  "simmer",
  "saute",
  "deglaze",
  "marinate",
  "glaze",
  "season",
  "garnish",
  "plate",
  "serve",
  "savor",
  "enjoy",
  "share",
  "entree",
  "appetizer",
  "main course",
  "side dish",
  "dessert",
  "bakery",
  "deli",
  "butcher",
  "groceries",
  "produce",
  "frozen foods",
  "canned goods",
  "condiments",
  "protein",
  "beverage",
  "flavorful",
  "gourmet",
  "fusion",
  "organic",
  "locally sourced",
  "sustainable",
  "fresh",
  "seasonal",
  "artisanal",
  "homemade",
  "authentic",
  "exotic",
  "international",
  "mild",
  "bold",
  "subtle",
  "umami",
  "refreshing",
  "comforting",
  "wholesome",
  "hearty",
  "light",
  "indulgent",
  "decadent",
  "nourishing",
  "satisfying",
  "delectable",
  "scrumptious",
  "mouthwatering",
  "appetizing",
  "tantalizing",
  "irresistible",
  "gastronomic",
  "palatable",
  "flavorsome",
  "edibles",
  "comestibles",
  "consumables",
  "provisions",
  "delicacy",
  "fare",
  "eats",
  "aroma",
  "scent",
  "fragrance",
  "odor",
  "essence",
  "perfume",
  "berry",
  "bun",
  "scramble",
  "cream",
  "oil",
  "vinegar",
  "sauce",
  "soup",
  "broth",
  "bisque",
  "chowder",
  "stew",
  "curry",
  "gumbo",
  "jambalaya",
  "ragout",
  "casserole",
  "custard",
  "flan",
  "oatmeal",
  "crunch",
  "cracker",
  "chocolate",
  "truffle",
  "bonbon",
  "toffee",
  "caramel",
  "gummy",
  "jellybean",
  "licorice",
  "marshmallow",
  "gumdrop",
  "pecan",
  "pistachio",
  "hazelnut",
  "macadamia",
  "peanut",
  "sunflower seed",
  "pumpkin seed",
  "sesame seed",
  "flaxseed",
  "chia seed",
  "barley",
  "oats",
  "wheat",
  "rice noodle",
  "udon",
  "soba",
  "breadstick",
  "crouton",
  "pretzel stick",
  "ciabatta",
  "flatbread",
  "crepe",
  "tartlet",
  "pierogi",
  "cannoli",
  "turnover",
  "danish",
  "strudel",
  "brownie",
  "blondie",
  "biscotti",
  "macaroon",
  "shortbread",
  "madeleine",
  "meringue",
  "clafoutis",
  "juice",
  "chai",
  "affogato",
  "cold brew",
  "hot chocolate",
  "eggnog",
  "punch",
  "spritzer",
  "smoothie bowl",
  "acai bowl",
  "green smoothie",
  "detox water",
  "lemon water",
  "flavored water",
  "soda",
  "ginger ale",
  "tonic",
  "iced coffee",
  "frappuccino",
  "bubble tea",
  "tea latte",
  "herbal tea",
  "iced latte",
  "matcha latte",
  "rooibos",
  "chai latte",
  "protein shake",
  "sports drink",
  "energy drink",
  "hemp milk",
  "rice milk",
  "cashew milk",
  "walnut milk",
  "horchata",
  "buttermilk",
  "whey",
  "ipa",
  "barleywine",
  "mead",
  "sake",
  "bourbon",
  "scotch",
  "irish whiskey",
  "canadian whiskey",
  "blended whiskey",
  "single malt",
  "single grain",
  "corn whiskey",
  "tennessee whiskey",
  "aguardiente",
  "sherry",
  "port",
  "madeira",
  "marsala",
  "amaro",
  "sotol",
  "makgeolli",
  "uzo",
  "liqueur",
  "cordial",
  "spirit",
  "perry",
  "pale ale",
  "kombucha",
  "decoction",
  "tisane",
  "extract",
  "slush",
  "slurpee",
  "granita",
  "blizzard",
  "mcflurry",
  "froyo",
  "ice cream sandwich",
  "ice pop",
  "sorbetto",
  "granola bar",
  "energy bar",
  "protein bar",
  "trail mix",
  "jerky",
  "salmon sushi",
  "cotton candy",
  "chocolate muffin",
  "doughnut",
  "salami",
  "acorn",
  "broccoli ",
  "fish fillet",
  "fried rice ",
  "tomyum",
  "longan",
  "gingerbread",
  "nugget",
  "iceberg lettuce ",
  "pomelo",
  "raspberry jam",
  "carrot cake",
  "beef burrito",
  "whisky",
  "cocoa",
  "pink grapefruit",
  "turbot",
  "panini",
  "artichoke",
  "apple pie",
  "chicken taco",
  "club sandwich",
  "dim sum ",
  "potato chips",
  "fried bread",
  "teabag",
  "crumpet",
  "marmalade",
  "lemon curd",
  "cornflakes",
  "scrambled egg",
  "sesame",
  "mulberry ",
  "apricot jam",
  "brioche",
  "spinach ",
  "fennel",
  "chocolate cake",
  "buffalo wings",
  "tiramisu ",
  "garden peas",
  "hotdog",
  "aubergine ",
  "pawpaw",
  "spaghetti ",
  "cheddar cheese",
  "black pudding",
  "mozzarella cheese",
  "raisin",
  "toro sashimi ",
  "conference pear",
  "nougat",
  "golden syrup",
  "baked beans",
  "dragon fruit",
  "lasagne",
  "eggs benedict",
  "cherry tomato",
  "sausages",
  "macaroni ",
  "radish",
  "lychee",
  "celery",
  "shish kebab",
  "goji berry",
  "emmental cheese",
  "tomato soup",
  "peanut butter",
  "toro nigiri",
  "cabbage ",
  "crayfish",
  "cherry jam",
  "brasil",
  "grapefruit juice",
  "curry chicken",
  "strawberry jam",
  "kimchi",
  "cheese burger",
  "blackberry jam",
  "coffee",
  "red snapper",
  "fish pie",
  "french fries",
  "cheesecake",
  "apple crumble",
  "dipping sauce",
  "brown sauce",
  "sourdough",
];

const currentWord = () => {
  const startDate = new Date("2023-11-13");
  startDate.setHours(0, 0, 0, 0);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const gameId = Math.floor(
    (today.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)
  );

  const todayWord = words[gameId];
  // const gameDaySession = today.getHours();
  // return gameDaySession < 12 ? wordsAM[gameId] : wordsPM[gameId];
  return {
    today: today,
    gameId: gameId,
    todayWord: todayWord,
  };
};

export { currentWord };
